name: 'Terraform'

on:
  workflow_call:
    inputs:
      TF_FORCE_APPLY:
        required: false
        type: string
      RUN_DBMATE:
        required: false
        type: string
      ENVIRONMENT:
        required: true
        type: string
      DBMATE_PAYLOAD:
        required: false
        type: string
      COMPONENT:
        required: true
        type: string
      TF_PRE_PLAN_COMMANDS:
        required: false
        type: string

permissions:
  id-token: write
  contents: read

env:
    AWS_DEFAULT_REGION: ap-southeast-2
    AWS_OIDC_ROLE: arn:aws:iam::670213391116:role/Joe-Org-Github-Actions-Env

jobs:
    tf_plan:
        name: Terraform Plan
        concurrency: tf_${{ inputs.COMPONENT }}_${{ inputs.ENVIRONMENT }}
        runs-on: ubuntu-latest
        steps:
          - name: Repo Checkout
            uses: actions/checkout@v4

          - name: Setup Pip
            run: |
              curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
              python3 get-pip.py
              export PATH=$PATH:~/.local/bin
              pip -V
              python3 --version
    
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
             aws-region: ${{ env.AWS_DEFAULT_REGION }}
             role-to-assume: ${{ env.AWS_OIDC_ROLE }}

          - name: 'Who am i'
            shell: bash
            run: |
             terraform -version
             aws sts get-caller-identity

          - name: Terraform Plan 
            id: plan
            uses: ifeanyi23/github-action-terraform-plan@v1.0.0 
            with:
               tfArgs: '-lock=false'
               gitUser: ${{ secrets.ACTIONS_SAAS_SA_USER }}
               gitToken: ${{ secrets.ACTIONS_SAAS_SA_TKN }}
               tfWorkspace: joe-org-platform-env-${{ inputs.ENVIRONMENT }}
               tfDir: ${{ inputs.COMPONENT }}/terraform